[package]
name = "gulfi-helper"
edition = "2024"
version.workspace = true

[dependencies]
eyre.workspace = true
color-eyre.workspace = true
serde_json.workspace = true
serde.workspace = true
camino.workspace = true
gulfi-common = { path = "../gulfi-common/"}
