[package]
name = "gulfi-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
color-eyre.workspace = true
serde_json.workspace = true
serde.workspace = true
termcolor = "1.4.1"
ansi_term = "0.12.1"

gulfi-common = { path = "../gulfi-common/"}
