[package]
name = "gulfi-common"
edition = "2024"
license.workspace = true
version.workspace = true

[dependencies]
eyre.workspace = true
camino.workspace = true
color-eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
ammonia = "4.0.0"
