version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.0.1
  slack: circleci/slack@5.1.1

workflows:
  version: 2
  rust:
    jobs:
      - check:
          name: "Run cargo clippy"
          context: [aws,slack]
      - test:
          name: "Run tests"
          context: [aws,slack]
      - udeps:
          name: "Run cargo-udeps"
          context: [aws,slack]

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check

      - slack/notify:
          event: fail
          template: basic_fail_1

  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test

      - slack/notify:
          event: fail
          template: basic_fail_1

  udeps:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just udeps

      - slack/notify:
          event: fail
          template: basic_fail_1
