version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.2.0
  node: circleci/node@7.1.0

workflows:
  version: 2

  build_and_test:
    jobs:
      - check:
          context: [aws]

      - test:
          context: [aws]

      - dependency_analysis:
          context: [aws]
          requires:
            - check

      - build_ui:
          context: []

      - update_taiga:
          context: [aws, taiga, slack]
          requires:
            - check
            - test
            - dependency_analysis
  
      - hold_for_approval:
          type: approval
          requires:
            - update_taiga
            - build_ui
          filters:
            branches:
              only: main

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check


  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test


  dependency_analysis:
    executor: shadesmar/rust
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - shadesmar/with_rust:
          steps:
            - run: |
                  echo "Running unused dependencies check..."
                  just udeps
                  
                  echo "Running license and dependency denial check..."
                  just deny
                   
                  echo "Running security audit..."
                  just audit
                
  build_ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-pnpm: true

      - run:
          name: building-ui
          command: cargo run -p xtask -- bundle

  update_taiga:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/update_taiga:
          project_name: Gulfi
          
