version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.1.0
  node: circleci/node@7.1.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - check:
          context: [aws]
      - test:
          context: [aws]
      - udeps:
          context: [aws]
      - deny:
          context: [aws]
      - build

      - update_taiga:
          context: [taiga]
          requires:
            - check
            - test
            - udeps
            - deny
            - build 

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check
  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test

  udeps:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just udeps

  deny:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just deny

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-pnpm: true

      - run:
          name: generando .lockfile
          command: cd crates/gulfi-server/ui/ && pnpm install

      - run:
          name: build
          command: cd crates/gulfi-server/ui/ && pnpm build

  update_taiga:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/sync_with_taiga:
          project_name: Gulfi
