version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.2.0
  node: circleci/node@7.1.0
  slack: circleci/slack@5.1.1
  sonarcloud: sonarsource/sonarcloud@3.0

workflows:
  version: 2

  build_and_test:
    jobs:
      - check:
          context: [aws, slack]

      - test:
          context: [aws, slack]

      - coverage_report:
          context: [aws, slack]

      - dependency_analysis:
          context: [aws, slack]
          requires:
            - check

      - build_ui:
          context: [slack]

      - compile_app:
          context: [slack, aws]
          requires:
            - build_ui
            - check
          
      - sonarcloud:
          context: [aws, slack, sonarqube]
          requires:
            - dependency_analysis
            - check
            - coverage_report
            - test

      - update_taiga:
          context: [aws, taiga, slack]
          requires:
            - check
            - test
            - dependency_analysis
  
      - hold_for_approval:
          type: approval
          requires:
            - sonarcloud
            - update_taiga
            - compile_app
          filters:
            branches:
              only: main

      - deploy_to_vps:
          context: [aquiles, slack, aws]
          requires:
            - hold_for_approval
          filters:
            branches:
              only: main

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check_report
            - persist_to_workspace:
                root: /root/project
                paths:
                  - clippy.json

      - slack/notify:
          event: fail
          template: basic_fail_1

  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test
            - run: |
                mv /root/project/target/nextest/ci/junit.xml /root/project/

            - store_test_results:
                path: junit.xml

            - persist_to_workspace:
                root: /root/project
                paths:
                  - junit.xml

      - slack/notify:
          event: fail
          template: basic_fail_1

  coverage_report:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just coverage

            - persist_to_workspace:
                root: /root/project
                paths:
                  - lcov.info

      - slack/notify:
          event: fail
          template: basic_fail_1

  dependency_analysis:
    executor: shadesmar/rust
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - shadesmar/with_rust:
          steps:
            - run: |
                  echo "Running unused dependencies check..."
                  just udeps_report
                  
                  echo "Running license and dependency denial check..."
                  just deny_report
                  
                  echo "Running security audit..."
                  just audit_report

                  echo "Preparing sonar analysis..."
                  just sonar

            - persist_to_workspace:
                root: /root/project
                paths:
                  - sonar-issues.json
                  - udeps.json
                  - clippy.json
                  - audit.json
                  - deny.json
                
      - slack/notify:
          event: fail
          template: basic_fail_1
          
  build_ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-pnpm: true

      - run:
          name: building-ui
          command: cd crates/gulfi-server/ui/ && pnpm install && pnpm build

      - persist_to_workspace:     
          root: .
          paths:
            - crates/gulfi-server/ui/dist

      - slack/notify:
          event: fail
          template: basic_fail_1

          
  compile_app:
    executor: shadesmar/rust
    steps:
      - checkout
      - attach_workspace:
          at: .  
      - run: |
          cargo build --release
      - persist_to_workspace:
          root: /root/project
          paths:
            - target/release/gulfi

      - slack/notify:
          event: fail
          template: basic_fail_1

  sonarcloud:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run: |
          ls
      - sonarcloud/scan
      - slack/notify:
          event: fail
          template: basic_fail_1

  update_taiga:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/update_taiga:
          project_name: Gulfi
          
      - slack/notify:
          event: fail
          template: basic_fail_1

  deploy_to_vps:
    executor: shadesmar/rust
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - run:
          name: Prepare deploy script
          command: |
            chmod +x deploy.sh

      - shadesmar/with_rust:
          steps:
            - run:
                name: Deploy to VPS
                command: ./deploy.sh
                no_output_timeout: 10m

      - slack/notify:
          event: fail
          template: basic_fail_1

      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
