version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.2.0
  node: circleci/node@7.1.0
  slack: circleci/slack@5.1.1
  sonarcloud: sonarsource/sonarcloud@3.0
  # codecov: codecov/codecov@5.4.3

workflows:
  version: 2

  build_and_test:
    jobs:
      - check:
          context: [aws, slack]

      - test:
          context: [aws, slack]

      - coverage_report:
          context: [aws, slack, codecov]

      - dependency_analysis:
          context: [aws, slack]
          requires:
            - check

      - build_ui:
          context: [slack]
          
      - sonarcloud:
          context: [aws, slack, sonarqube]
          requires:
            - dependency_analysis
            - check
            - coverage_report

      - update_taiga:
          context: [aws, taiga, slack]
          requires:
            - check
            - test
            - dependency_analysis

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check_report
            - persist_to_workspace:
                root: /root/project
                paths:
                  - clippy.json

      - slack/notify:
          event: fail
          template: basic_fail_1

  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test
            - run: |
                mv /root/project/target/nextest/ci/junit.xml /root/project

            - store_test_results:
                path: junit.xml

            - persist_to_workspace:
                root: /root/project
                paths:
                  - junit.xml

      - slack/notify:
          event: fail
          template: basic_fail_1

  coverage_report:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just coverage

            # - codecov/upload

            - persist_to_workspace:
                root: /root/project
                paths:
                  - lcov.info

      - slack/notify:
          event: fail
          template: basic_fail_1

  dependency_analysis:
    executor: shadesmar/rust
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - shadesmar/with_rust:
          steps:
            - run: |
                  echo "Running unused dependencies check..."
                  just udeps_report
                  
                  echo "Running license and dependency denial check..."
                  just deny_report
                  
                  echo "Running security audit..."
                  just audit_report

                  echo "Preparing sonar analysis..."
                  just sonar

            - persist_to_workspace:
                root: /root/project
                paths:
                  - sonar-issues.json
                
      - slack/notify:
          event: fail
          template: basic_fail_1
          
  build_ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-pnpm: true

      - run:
          name: generando .lockfile
          command: cd crates/gulfi-server/ui/ && pnpm install

      - run:
          name: build
          command: cd crates/gulfi-server/ui/ && pnpm build

      - slack/notify:
          event: fail
          template: basic_fail_1

  sonarcloud:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run: |
          ls
      - sonarcloud/scan
      - slack/notify:
          event: fail
          template: basic_fail_1

  update_taiga:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/update_taiga:
          project_name: Gulfi
          
      - slack/notify:
          event: fail
          template: basic_fail_1

