version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.0.1
  node: circleci/node@7.1.0

workflows:
  version: 2
  rust:
    jobs:
      - check:
          context: [aws]
      - test:
          context: [aws]
      - udeps:
          context: [aws]
      - deny:
          context: [aws]

  build-frontend:
      jobs:
        - build

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check
  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test

  udeps:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just udeps

  deny:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just deny


  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project/crates/gulfi-server/ui
    steps:
      - checkout
      - node/install:
          install-pnpm: true
      - run:
          name: generando .lockfile
          command: pnpm install

      - run:
          name: build
          command: pnpm build
