version: 2.1

orbs:
  shadesmar: shadesmar/rust@1.0.1
  node: circleci/node@7.1.0

workflows:
  version: 2
  rust:
    jobs:
      - check:
          context: [aws]
      - test:
          context: [aws]
      - udeps:
          context: [aws]
      - deny:
          context: [aws]

  svelte:
      jobs:
        - build-ui

jobs:
  check:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just check
  test:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just test

  udeps:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just udeps

  deny:
    executor: shadesmar/rust
    steps:
      - checkout
      - shadesmar/with_rust:
          steps:
            - run: |
                just deny
  build-ui:
    docker: 
      - image: cimg/base

    parameters:
      app-directory:
        type: string
        default: "/crates/gulfi-server/ui"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
          app-dir: << parameters.app-directory >>
          cache-path: << parameters.app-directory>>/node_modules
          cache-version: v1-{{ .Branch }}-{{ checksum "<< parameters.app-directory >>/package-lock.json" }}
      - run:
          name: build project
          command: pnpm build
          working_directory: << parameters.app-directory >>

      - run:
          name: Show build size
          command: du -h -d 1 build
          working_directory: << parameters.app-directory >>



