[package]
name = "gulfi"
edition = "2024"
authors = ["Lautaro <acostaquintanalautaro@gmail.com>"]
license.workspace = true
version.workspace = true

[dependencies]
dotenvy = "0.15.7"
tower-request-id = "0.3.0"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json", "time"] }

eyre.workspace = true
tracing.workspace = true
color-eyre.workspace = true
clap.workspace = true
axum.workspace = true
tokio.workspace = true
chrono.workspace = true
serde_json.workspace = true
argon2.workspace = true
rusqlite.workspace = true
password-hash.workspace = true

gulfi-sqlite = { path = "../gulfi-sqlite/"}
gulfi-common = { path = "../gulfi-common/"}
gulfi-server = { path = "../gulfi-server/"}
gulfi-cli = { path = "../gulfi-cli/"}

