[package]
name = "gulfi-ui"
edition = "2024"
version.workspace = true

[dependencies]
serde.workspace = true
axum.workspace = true
rusqlite.workspace = true
chrono.workspace = true

include_dir = "0.7.4"
# gulfi-sqlite = { path = "../gulfi-sqlite/" }
