[package]
name = "gulfi-query"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.12"
ammonia = "4.0.0"

[dev-dependencies]
expect-test = "1.5.1"
proptest = "1.6.0"
