[package]
name = "gulfi-query"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.12"
ammonia = "4.0.0"
expect-test = "1.5.1"

[dev-dependencies]
proptest = "1.6.0"
pretty_assertions = "1.4.1"
